version: '3'

services:
  samba:
    image: naturalis/samba-join-ad:0.0.1
    hostname: ${SMB_HOSTNAME}
    extra_hosts:
      - "${SMB_HOSTNAME}:${SMB_IP}"
    ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139"
        - "445:445"
    networks:
      - default
    restart: unless-stopped
    volumes:
      - /data:/data
      - /var/log/samba:/var/log/samba
    env_file:
      .env
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'

networks:
  default: