version: '3'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/Amsterdam'
      USER: '${SMB_USER};${SMB_PASSWORD}'
      SHARE: '${SMB_SHARE};/data;yes;no;no;;;;data share'
      WORKGROUP: '${SMB_WORKGROUP}'
    ports:
        - "139:139"
        - "445:445"
    networks:
      - default
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /data:/data
    command: "-S -r"

networks:
  default: